### ISSUE TITLE
ImportError: cannot import name 'RootModel' from 'pydantic'

### ISSUE THREAD

**Issue by billcsm** [soulteary/docker-sdxl#1]
My test platform is 
GPU: 1x A100, 
OS: ubuntu 22.04 
CUDA: 12.2.1

Followed the README.md to build Docker Stable Diffusion XL (SDXL) was easy and simple. No issue for the process. But when I ran soulteary/sdxl:all-xformers, it always got the following error:

root@a674cf84f3b3:/app# python refiner.py
Traceback (most recent call last):
  File "/app/refiner.py", line 1, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/usr/local/lib/python3.10/dist-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/usr/local/lib/python3.10/dist-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/annotated_image.py", line 11, in <module>
    from gradio import processing_utils, utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 22, in <module>
    from gradio.data_classes import FileData, GradioModel, GradioRootModel
  File "/usr/local/lib/python3.10/dist-packages/gradio/data_classes.py", line 19, in <module>
    from pydantic import BaseModel, RootModel, ValidationError  # type: ignore
ImportError: cannot import name 'RootModel' from 'pydantic' (/usr/local/lib/python3.10/dist-packages/pydantic/__init__.cpython-310-x86_64-linux-gnu.so)
root@a674cf84f3b3:/app#
root@a674cf84f3b3:/app# python basic.py
Traceback (most recent call last):
  File "/app/basic.py", line 1, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/usr/local/lib/python3.10/dist-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/usr/local/lib/python3.10/dist-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/annotated_image.py", line 11, in <module>
    from gradio import processing_utils, utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 22, in <module>
    from gradio.data_classes import FileData, GradioModel, GradioRootModel
  File "/usr/local/lib/python3.10/dist-packages/gradio/data_classes.py", line 19, in <module>
    from pydantic import BaseModel, RootModel, ValidationError  # type: ignore
ImportError: cannot import name 'RootModel' from 'pydantic' (/usr/local/lib/python3.10/dist-packages/pydantic/__init__.cpython-310-x86_64-linux-gnu.so)
root@a674cf84f3b3:/app#

Does anyone know how to fix this issue? Thank you in advance.

**Comment by soulteary** [comment]
try https://github.com/soulteary/docker-stable-diffusion-xl-turbo
